spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxy-workflow?characterEncoding=utf8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'root123456'
  activiti:
    database-schema-update: true
    check-process-definitions: false
    history-level: full
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  security:
    basic:
      enabled: false
  logging:
    level: debug
  server:
    port: 8089
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
  thymeleaf:
    cache: false